#ifndef JSGEN_TESTS_JSGEN_MODELS_G_H
#define JSGEN_TESTS_JSGEN_MODELS_G_H

// *** Auto-generated by jsgen. Do not edit manually. ***

#include "../jsgen/jsgen.h"
#include "../jsb.h"
#include "../jsp.h"
int _parse_BasicModel(Jsp *jsp, BasicModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "id") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->id = jsp->number;
        } else if (strcmp(jsp->string, "name") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->name = jsgen_malloc(s_len + 1);
                strcpy(out->name, jsp->string);
            } else {
                out->name = NULL;
            }
        } else if (strcmp(jsp->string, "score") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->score = jsp->number;
        } else if (strcmp(jsp->string, "rating") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->rating = jsp->number;
        } else if (strcmp(jsp->string, "active") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->active = jsp->boolean;
        } else if (strcmp(jsp->string, "timestamp") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->timestamp = jsp->number;
        } else if (strcmp(jsp->string, "count") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->count = jsp->number;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_BasicModel_a(const char *json, BasicModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_BasicModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_BasicModel(json, out) parse_BasicModel_a((json), (out), JSGEN_MALLOC)

int _parse_BasicModel_list(Jsp *jsp, BasicModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(BasicModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_BasicModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_BasicModel_list_a(const char *json, BasicModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_BasicModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_BasicModel_list(json, out, out_count) parse_BasicModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_BasicModel(Jsb *jsb, BasicModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "id")) return -1;
        if (jsb_int(jsb, in->id)) return -1;
        if (in->name != NULL) {
            if (jsb_key(jsb, "name")) return -1;
            if (jsb_string(jsb, in->name)) return -1;
  }
        if (jsb_key(jsb, "score")) return -1;
        if (jsb_number(jsb, in->score, 5)) return -1;
        if (jsb_key(jsb, "rating")) return -1;
        if (jsb_number(jsb, in->rating, 5)) return -1;
        if (jsb_key(jsb, "active")) return -1;
        if (jsb_bool(jsb, in->active)) return -1;
        if (jsb_key(jsb, "timestamp")) return -1;
        if (jsb_int(jsb, in->timestamp)) return -1;
        if (jsb_key(jsb, "count")) return -1;
        if (jsb_int(jsb, in->count)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_BasicModel_indent(BasicModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_BasicModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_BasicModel(in) stringify_BasicModel_indent((in), 0)

char* stringify_BasicModel_list_indent(BasicModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_BasicModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_BasicModel_list(in, count) stringify_BasicModel_list_indent((in), (count), 0)

int _parse_AliasModel(Jsp *jsp, AliasModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "id") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->id = jsp->number;
        } else if (strcmp(jsp->string, "firstName") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->first_name = jsgen_malloc(s_len + 1);
                strcpy(out->first_name, jsp->string);
            } else {
                out->first_name = NULL;
            }
        } else if (strcmp(jsp->string, "lastName") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->last_name = jsgen_malloc(s_len + 1);
                strcpy(out->last_name, jsp->string);
            } else {
                out->last_name = NULL;
            }
        } else if (strcmp(jsp->string, "isActive") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->is_active = jsp->boolean;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_AliasModel_a(const char *json, AliasModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_AliasModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_AliasModel(json, out) parse_AliasModel_a((json), (out), JSGEN_MALLOC)

int _parse_AliasModel_list(Jsp *jsp, AliasModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(AliasModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_AliasModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_AliasModel_list_a(const char *json, AliasModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_AliasModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_AliasModel_list(json, out, out_count) parse_AliasModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_AliasModel(Jsb *jsb, AliasModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "id")) return -1;
        if (jsb_int(jsb, in->id)) return -1;
        if (in->first_name != NULL) {
            if (jsb_key(jsb, "firstName")) return -1;
            if (jsb_string(jsb, in->first_name)) return -1;
  }
        if (in->last_name != NULL) {
            if (jsb_key(jsb, "lastName")) return -1;
            if (jsb_string(jsb, in->last_name)) return -1;
  }
        if (jsb_key(jsb, "isActive")) return -1;
        if (jsb_bool(jsb, in->is_active)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_AliasModel_indent(AliasModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_AliasModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_AliasModel(in) stringify_AliasModel_indent((in), 0)

char* stringify_AliasModel_list_indent(AliasModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_AliasModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_AliasModel_list(in, count) stringify_AliasModel_list_indent((in), (count), 0)

int _parse_Address(Jsp *jsp, Address *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "street") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->street = jsgen_malloc(s_len + 1);
                strcpy(out->street, jsp->string);
            } else {
                out->street = NULL;
            }
        } else if (strcmp(jsp->string, "city") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->city = jsgen_malloc(s_len + 1);
                strcpy(out->city, jsp->string);
            } else {
                out->city = NULL;
            }
        } else if (strcmp(jsp->string, "zip") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->zip = jsp->number;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_Address_a(const char *json, Address *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_Address(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_Address(json, out) parse_Address_a((json), (out), JSGEN_MALLOC)

int _parse_Address_list(Jsp *jsp, Address **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(Address) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_Address(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_Address_list_a(const char *json, Address **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_Address_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_Address_list(json, out, out_count) parse_Address_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_Address(Jsb *jsb, Address *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->street != NULL) {
            if (jsb_key(jsb, "street")) return -1;
            if (jsb_string(jsb, in->street)) return -1;
  }
        if (in->city != NULL) {
            if (jsb_key(jsb, "city")) return -1;
            if (jsb_string(jsb, in->city)) return -1;
  }
        if (jsb_key(jsb, "zip")) return -1;
        if (jsb_int(jsb, in->zip)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_Address_indent(Address *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_Address(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_Address(in) stringify_Address_indent((in), 0)

char* stringify_Address_list_indent(Address *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_Address(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_Address_list(in, count) stringify_Address_list_indent((in), (count), 0)

int _parse_PersonModel(Jsp *jsp, PersonModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "id") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->id = jsp->number;
        } else if (strcmp(jsp->string, "name") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->name = jsgen_malloc(s_len + 1);
                strcpy(out->name, jsp->string);
            } else {
                out->name = NULL;
            }
        } else if (strcmp(jsp->string, "address") == 0) {
            err = jsp_value(jsp);
            if (!err && jsp->type == JSP_TYPE_NULL) {
                out->address = NULL;
            } else {
                out->address = jsgen_malloc(sizeof(Address));
                err = _parse_Address(jsp, out->address, jsgen_malloc);
                if (err) return err;
            }
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_PersonModel_a(const char *json, PersonModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_PersonModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_PersonModel(json, out) parse_PersonModel_a((json), (out), JSGEN_MALLOC)

int _parse_PersonModel_list(Jsp *jsp, PersonModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(PersonModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_PersonModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_PersonModel_list_a(const char *json, PersonModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_PersonModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_PersonModel_list(json, out, out_count) parse_PersonModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_PersonModel(Jsb *jsb, PersonModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "id")) return -1;
        if (jsb_int(jsb, in->id)) return -1;
        if (in->name != NULL) {
            if (jsb_key(jsb, "name")) return -1;
            if (jsb_string(jsb, in->name)) return -1;
  }
        if (in->address != NULL) {
            if (jsb_key(jsb, "address")) return -1;
            if (in->address == NULL) jsb_null(jsb);
            else if (_stringify_Address(jsb, in->address)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_PersonModel_indent(PersonModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_PersonModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_PersonModel(in) stringify_PersonModel_indent((in), 0)

char* stringify_PersonModel_list_indent(PersonModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_PersonModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_PersonModel_list(in, count) stringify_PersonModel_list_indent((in), (count), 0)

int _parse_Tag(Jsp *jsp, Tag *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "key") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->key = jsgen_malloc(s_len + 1);
                strcpy(out->key, jsp->string);
            } else {
                out->key = NULL;
            }
        } else if (strcmp(jsp->string, "value") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->value = jsgen_malloc(s_len + 1);
                strcpy(out->value, jsp->string);
            } else {
                out->value = NULL;
            }
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_Tag_a(const char *json, Tag *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_Tag(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_Tag(json, out) parse_Tag_a((json), (out), JSGEN_MALLOC)

int _parse_Tag_list(Jsp *jsp, Tag **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(Tag) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_Tag(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_Tag_list_a(const char *json, Tag **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_Tag_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_Tag_list(json, out, out_count) parse_Tag_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_Tag(Jsb *jsb, Tag *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->key != NULL) {
            if (jsb_key(jsb, "key")) return -1;
            if (jsb_string(jsb, in->key)) return -1;
  }
        if (in->value != NULL) {
            if (jsb_key(jsb, "value")) return -1;
            if (jsb_string(jsb, in->value)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_Tag_indent(Tag *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_Tag(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_Tag(in) stringify_Tag_indent((in), 0)

char* stringify_Tag_list_indent(Tag *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_Tag(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_Tag_list(in, count) stringify_Tag_list_indent((in), (count), 0)

int _parse_TaggedModel(Jsp *jsp, TaggedModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "id") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->id = jsp->number;
        } else if (strcmp(jsp->string, "tags") == 0) {
            err = jsp_begin_array(jsp);
            if (err) return err;
            size_t len = jsp_array_length(jsp);
            out->tag_count = len;
            out->tags = jsgen_malloc(sizeof(Tag) * len);
            for (size_t i = 0; i < len; i++) {
                err = _parse_Tag(jsp, &out->tags[i], jsgen_malloc);
                if (err) break;
            }
            err = jsp_end_array(jsp);
            if (err) return err;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_TaggedModel_a(const char *json, TaggedModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_TaggedModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_TaggedModel(json, out) parse_TaggedModel_a((json), (out), JSGEN_MALLOC)

int _parse_TaggedModel_list(Jsp *jsp, TaggedModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(TaggedModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_TaggedModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_TaggedModel_list_a(const char *json, TaggedModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_TaggedModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_TaggedModel_list(json, out, out_count) parse_TaggedModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_TaggedModel(Jsb *jsb, TaggedModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "id")) return -1;
        if (jsb_int(jsb, in->id)) return -1;
        if (in->tags != NULL) {
            if (jsb_key(jsb, "tags")) return -1;
            if (jsb_begin_array(jsb)) return -1;
            for (size_t i = 0; i < (size_t)in->tag_count; ++i) {
                if (_stringify_Tag(jsb, &in->tags[i])) return -1;
            }
            if (jsb_end_array(jsb)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_TaggedModel_indent(TaggedModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_TaggedModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_TaggedModel(in) stringify_TaggedModel_indent((in), 0)

char* stringify_TaggedModel_list_indent(TaggedModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_TaggedModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_TaggedModel_list(in, count) stringify_TaggedModel_list_indent((in), (count), 0)

int _parse_color(Jsp *jsp, struct color *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "r") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->r = jsp->number;
        } else if (strcmp(jsp->string, "g") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->g = jsp->number;
        } else if (strcmp(jsp->string, "b") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->b = jsp->number;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_color_a(const char *json, struct color *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_color(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_color(json, out) parse_color_a((json), (out), JSGEN_MALLOC)

int _parse_color_list(Jsp *jsp, struct color **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(struct color) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_color(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_color_list_a(const char *json, struct color **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_color_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_color_list(json, out, out_count) parse_color_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_color(Jsb *jsb, struct color *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "r")) return -1;
        if (jsb_int(jsb, in->r)) return -1;
        if (jsb_key(jsb, "g")) return -1;
        if (jsb_int(jsb, in->g)) return -1;
        if (jsb_key(jsb, "b")) return -1;
        if (jsb_int(jsb, in->b)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_color_indent(struct color *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_color(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_color(in) stringify_color_indent((in), 0)

char* stringify_color_list_indent(struct color *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_color(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_color_list(in, count) stringify_color_list_indent((in), (count), 0)

int _parse_ThemeModel(Jsp *jsp, ThemeModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "name") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->name = jsgen_malloc(s_len + 1);
                strcpy(out->name, jsp->string);
            } else {
                out->name = NULL;
            }
        } else if (strcmp(jsp->string, "fg") == 0) {
            err = jsp_value(jsp);
            if (!err && jsp->type == JSP_TYPE_NULL) {
                out->fg = NULL;
            } else {
                out->fg = jsgen_malloc(sizeof(struct color));
                err = _parse_color(jsp, out->fg, jsgen_malloc);
                if (err) return err;
            }
        } else if (strcmp(jsp->string, "bg") == 0) {
            err = jsp_value(jsp);
            if (!err && jsp->type == JSP_TYPE_NULL) {
                out->bg = NULL;
            } else {
                out->bg = jsgen_malloc(sizeof(struct color));
                err = _parse_color(jsp, out->bg, jsgen_malloc);
                if (err) return err;
            }
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_ThemeModel_a(const char *json, ThemeModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_ThemeModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_ThemeModel(json, out) parse_ThemeModel_a((json), (out), JSGEN_MALLOC)

int _parse_ThemeModel_list(Jsp *jsp, ThemeModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(ThemeModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_ThemeModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_ThemeModel_list_a(const char *json, ThemeModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_ThemeModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_ThemeModel_list(json, out, out_count) parse_ThemeModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_ThemeModel(Jsb *jsb, ThemeModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->name != NULL) {
            if (jsb_key(jsb, "name")) return -1;
            if (jsb_string(jsb, in->name)) return -1;
  }
        if (in->fg != NULL) {
            if (jsb_key(jsb, "fg")) return -1;
            if (in->fg == NULL) jsb_null(jsb);
            else if (_stringify_color(jsb, in->fg)) return -1;
  }
        if (in->bg != NULL) {
            if (jsb_key(jsb, "bg")) return -1;
            if (in->bg == NULL) jsb_null(jsb);
            else if (_stringify_color(jsb, in->bg)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_ThemeModel_indent(ThemeModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_ThemeModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_ThemeModel(in) stringify_ThemeModel_indent((in), 0)

char* stringify_ThemeModel_list_indent(ThemeModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_ThemeModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_ThemeModel_list(in, count) stringify_ThemeModel_list_indent((in), (count), 0)

int _parse_IgnoreModel(Jsp *jsp, IgnoreModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "id") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->id = jsp->number;
        } else if (strcmp(jsp->string, "name") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->name = jsgen_malloc(s_len + 1);
                strcpy(out->name, jsp->string);
            } else {
                out->name = NULL;
            }
        } else if (strcmp(jsp->string, "visible") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->visible = jsp->boolean;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_IgnoreModel_a(const char *json, IgnoreModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_IgnoreModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_IgnoreModel(json, out) parse_IgnoreModel_a((json), (out), JSGEN_MALLOC)

int _parse_IgnoreModel_list(Jsp *jsp, IgnoreModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(IgnoreModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_IgnoreModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_IgnoreModel_list_a(const char *json, IgnoreModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_IgnoreModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_IgnoreModel_list(json, out, out_count) parse_IgnoreModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_IgnoreModel(Jsb *jsb, IgnoreModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "id")) return -1;
        if (jsb_int(jsb, in->id)) return -1;
        if (in->name != NULL) {
            if (jsb_key(jsb, "name")) return -1;
            if (jsb_string(jsb, in->name)) return -1;
  }
        if (jsb_key(jsb, "visible")) return -1;
        if (jsb_bool(jsb, in->visible)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_IgnoreModel_indent(IgnoreModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_IgnoreModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_IgnoreModel(in) stringify_IgnoreModel_indent((in), 0)

char* stringify_IgnoreModel_list_indent(IgnoreModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_IgnoreModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_IgnoreModel_list(in, count) stringify_IgnoreModel_list_indent((in), (count), 0)

int _parse_MinimalModel(Jsp *jsp, MinimalModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "dummy") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->dummy = jsp->number;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_MinimalModel_a(const char *json, MinimalModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_MinimalModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_MinimalModel(json, out) parse_MinimalModel_a((json), (out), JSGEN_MALLOC)

int _parse_MinimalModel_list(Jsp *jsp, MinimalModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(MinimalModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_MinimalModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_MinimalModel_list_a(const char *json, MinimalModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_MinimalModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_MinimalModel_list(json, out, out_count) parse_MinimalModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_MinimalModel(Jsb *jsb, MinimalModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "dummy")) return -1;
        if (jsb_int(jsb, in->dummy)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_MinimalModel_indent(MinimalModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_MinimalModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_MinimalModel(in) stringify_MinimalModel_indent((in), 0)

char* stringify_MinimalModel_list_indent(MinimalModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_MinimalModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_MinimalModel_list(in, count) stringify_MinimalModel_list_indent((in), (count), 0)

int _parse_Inner(Jsp *jsp, Inner *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "x") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->x = jsp->number;
        } else if (strcmp(jsp->string, "y") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->y = jsp->number;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_Inner_a(const char *json, Inner *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_Inner(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_Inner(json, out) parse_Inner_a((json), (out), JSGEN_MALLOC)

int _parse_Inner_list(Jsp *jsp, Inner **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(Inner) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_Inner(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_Inner_list_a(const char *json, Inner **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_Inner_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_Inner_list(json, out, out_count) parse_Inner_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_Inner(Jsb *jsb, Inner *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "x")) return -1;
        if (jsb_int(jsb, in->x)) return -1;
        if (jsb_key(jsb, "y")) return -1;
        if (jsb_int(jsb, in->y)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_Inner_indent(Inner *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_Inner(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_Inner(in) stringify_Inner_indent((in), 0)

char* stringify_Inner_list_indent(Inner *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_Inner(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_Inner_list(in, count) stringify_Inner_list_indent((in), (count), 0)

int _parse_InlineNestedModel(Jsp *jsp, InlineNestedModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "name") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->name = jsgen_malloc(s_len + 1);
                strcpy(out->name, jsp->string);
            } else {
                out->name = NULL;
            }
        } else if (strcmp(jsp->string, "pos") == 0) {
            err = _parse_Inner(jsp, &out->pos, jsgen_malloc);
            if (err) return err;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_InlineNestedModel_a(const char *json, InlineNestedModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_InlineNestedModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_InlineNestedModel(json, out) parse_InlineNestedModel_a((json), (out), JSGEN_MALLOC)

int _parse_InlineNestedModel_list(Jsp *jsp, InlineNestedModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(InlineNestedModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_InlineNestedModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_InlineNestedModel_list_a(const char *json, InlineNestedModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_InlineNestedModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_InlineNestedModel_list(json, out, out_count) parse_InlineNestedModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_InlineNestedModel(Jsb *jsb, InlineNestedModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->name != NULL) {
            if (jsb_key(jsb, "name")) return -1;
            if (jsb_string(jsb, in->name)) return -1;
  }
        if (jsb_key(jsb, "pos")) return -1;
        if (_stringify_Inner(jsb, &in->pos)) return -1;
    }
    return jsb_end_object(jsb);
}

char* stringify_InlineNestedModel_indent(InlineNestedModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_InlineNestedModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_InlineNestedModel(in) stringify_InlineNestedModel_indent((in), 0)

char* stringify_InlineNestedModel_list_indent(InlineNestedModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_InlineNestedModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_InlineNestedModel_list(in, count) stringify_InlineNestedModel_list_indent((in), (count), 0)

int _stringify_StringifyOnlyModel(Jsb *jsb, StringifyOnlyModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (jsb_key(jsb, "code")) return -1;
        if (jsb_int(jsb, in->code)) return -1;
        if (in->message != NULL) {
            if (jsb_key(jsb, "message")) return -1;
            if (jsb_string(jsb, in->message)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_StringifyOnlyModel_indent(StringifyOnlyModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_StringifyOnlyModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_StringifyOnlyModel(in) stringify_StringifyOnlyModel_indent((in), 0)

char* stringify_StringifyOnlyModel_list_indent(StringifyOnlyModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_StringifyOnlyModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_StringifyOnlyModel_list(in, count) stringify_StringifyOnlyModel_list_indent((in), (count), 0)

int _parse_ParseOnlyModel(Jsp *jsp, ParseOnlyModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "code") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            out->code = jsp->number;
        } else if (strcmp(jsp->string, "message") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->message = jsgen_malloc(s_len + 1);
                strcpy(out->message, jsp->string);
            } else {
                out->message = NULL;
            }
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_ParseOnlyModel_a(const char *json, ParseOnlyModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_ParseOnlyModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_ParseOnlyModel(json, out) parse_ParseOnlyModel_a((json), (out), JSGEN_MALLOC)

int _parse_ParseOnlyModel_list(Jsp *jsp, ParseOnlyModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(ParseOnlyModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_ParseOnlyModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_ParseOnlyModel_list_a(const char *json, ParseOnlyModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_ParseOnlyModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_ParseOnlyModel_list(json, out, out_count) parse_ParseOnlyModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _parse_DualAddressModel(Jsp *jsp, DualAddressModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "name") == 0) {
            err = jsp_value(jsp);
            if (err) return err;
            size_t s_len = jsp->string ? strlen(jsp->string) : 0;
            if(s_len > 0) {
                out->name = jsgen_malloc(s_len + 1);
                strcpy(out->name, jsp->string);
            } else {
                out->name = NULL;
            }
        } else if (strcmp(jsp->string, "home") == 0) {
            err = jsp_value(jsp);
            if (!err && jsp->type == JSP_TYPE_NULL) {
                out->home = NULL;
            } else {
                out->home = jsgen_malloc(sizeof(Address));
                err = _parse_Address(jsp, out->home, jsgen_malloc);
                if (err) return err;
            }
        } else if (strcmp(jsp->string, "work") == 0) {
            err = jsp_value(jsp);
            if (!err && jsp->type == JSP_TYPE_NULL) {
                out->work = NULL;
            } else {
                out->work = jsgen_malloc(sizeof(Address));
                err = _parse_Address(jsp, out->work, jsgen_malloc);
                if (err) return err;
            }
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_DualAddressModel_a(const char *json, DualAddressModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_DualAddressModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_DualAddressModel(json, out) parse_DualAddressModel_a((json), (out), JSGEN_MALLOC)

int _parse_DualAddressModel_list(Jsp *jsp, DualAddressModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(DualAddressModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_DualAddressModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_DualAddressModel_list_a(const char *json, DualAddressModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_DualAddressModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_DualAddressModel_list(json, out, out_count) parse_DualAddressModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_DualAddressModel(Jsb *jsb, DualAddressModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->name != NULL) {
            if (jsb_key(jsb, "name")) return -1;
            if (jsb_string(jsb, in->name)) return -1;
  }
        if (in->home != NULL) {
            if (jsb_key(jsb, "home")) return -1;
            if (in->home == NULL) jsb_null(jsb);
            else if (_stringify_Address(jsb, in->home)) return -1;
  }
        if (in->work != NULL) {
            if (jsb_key(jsb, "work")) return -1;
            if (in->work == NULL) jsb_null(jsb);
            else if (_stringify_Address(jsb, in->work)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_DualAddressModel_indent(DualAddressModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_DualAddressModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_DualAddressModel(in) stringify_DualAddressModel_indent((in), 0)

char* stringify_DualAddressModel_list_indent(DualAddressModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_DualAddressModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_DualAddressModel_list(in, count) stringify_DualAddressModel_list_indent((in), (count), 0)

int _parse_IntArrayModel(Jsp *jsp, IntArrayModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "values") == 0) {
            err = jsp_begin_array(jsp);
            if (err) return err;
            size_t len = jsp_array_length(jsp);
            out->value_count = len;
            out->values = jsgen_malloc(sizeof(int) * len);
            for (size_t i = 0; i < len; i++) {
                err = jsp_value(jsp);
                if (err) break;
                out->values[i] = jsp->number;
            }
            err = jsp_end_array(jsp);
            if (err) return err;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_IntArrayModel_a(const char *json, IntArrayModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_IntArrayModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_IntArrayModel(json, out) parse_IntArrayModel_a((json), (out), JSGEN_MALLOC)

int _parse_IntArrayModel_list(Jsp *jsp, IntArrayModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(IntArrayModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_IntArrayModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_IntArrayModel_list_a(const char *json, IntArrayModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_IntArrayModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_IntArrayModel_list(json, out, out_count) parse_IntArrayModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_IntArrayModel(Jsb *jsb, IntArrayModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->values != NULL) {
            if (jsb_key(jsb, "values")) return -1;
            if (jsb_begin_array(jsb)) return -1;
            for (size_t i = 0; i < (size_t)in->value_count; ++i) {
                if (jsb_int(jsb, in->values[i])) return -1;
            }
            if (jsb_end_array(jsb)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_IntArrayModel_indent(IntArrayModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_IntArrayModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_IntArrayModel(in) stringify_IntArrayModel_indent((in), 0)

char* stringify_IntArrayModel_list_indent(IntArrayModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_IntArrayModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_IntArrayModel_list(in, count) stringify_IntArrayModel_list_indent((in), (count), 0)

int _parse_DoubleArrayModel(Jsp *jsp, DoubleArrayModel *out, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_object(jsp);
    if (err) return err;
    while (jsp_key(jsp) == 0) {
        if (strcmp(jsp->string, "scores") == 0) {
            err = jsp_begin_array(jsp);
            if (err) return err;
            size_t len = jsp_array_length(jsp);
            out->score_count = len;
            out->scores = jsgen_malloc(sizeof(double) * len);
            for (size_t i = 0; i < len; i++) {
                err = jsp_value(jsp);
                if (err) break;
                out->scores[i] = jsp->number;
            }
            err = jsp_end_array(jsp);
            if (err) return err;
        } else {
            err = jsp_skip(jsp);
            if (err) return err;
        }
    }
    err = jsp_end_object(jsp);
    return err;
}

int parse_DoubleArrayModel_a(const char *json, DoubleArrayModel *out, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_DoubleArrayModel(&jsp, out, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_DoubleArrayModel(json, out) parse_DoubleArrayModel_a((json), (out), JSGEN_MALLOC)

int _parse_DoubleArrayModel_list(Jsp *jsp, DoubleArrayModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    int err = jsp_begin_array(jsp);
    if (err) return err;
    size_t len = jsp_array_length(jsp);
    *out_count = len;
    *out = jsgen_malloc(sizeof(DoubleArrayModel) * len);
    for (size_t i = 0; i < len; i++) {
        err = _parse_DoubleArrayModel(jsp, &(*out)[i], jsgen_malloc);
        if (err) return err;
    }
    err = jsp_end_array(jsp);
    if (err) { *out = NULL; *out_count = 0; }
    return err;
}
int parse_DoubleArrayModel_list_a(const char *json, DoubleArrayModel **out, size_t *out_count, JsGenMalloc jsgen_malloc) {
    Jsp jsp = {0};
    int err = jsp_init(&jsp, json, strlen(json));
    if (err) return err;
    err = _parse_DoubleArrayModel_list(&jsp, out, out_count, jsgen_malloc);
    jsp_free(&jsp);
    return err;
}

#define parse_DoubleArrayModel_list(json, out, out_count) parse_DoubleArrayModel_list_a((json), (out), (out_count), JSGEN_MALLOC)

int _stringify_DoubleArrayModel(Jsb *jsb, DoubleArrayModel *in) {
    if (jsb_begin_object(jsb)) return -1;
    {
        if (in->scores != NULL) {
            if (jsb_key(jsb, "scores")) return -1;
            if (jsb_begin_array(jsb)) return -1;
            for (size_t i = 0; i < (size_t)in->score_count; ++i) {
                if (jsb_number(jsb, in->scores[i], 5)) return -1;
            }
            if (jsb_end_array(jsb)) return -1;
  }
    }
    return jsb_end_object(jsb);
}

char* stringify_DoubleArrayModel_indent(DoubleArrayModel *in, int indent) {
    Jsb jsb = {.pp = indent};
    if(_stringify_DoubleArrayModel(&jsb, in)) {
        jsb_free(&jsb);
        return NULL;
    }
    return jsb_get(&jsb);
}

#define stringify_DoubleArrayModel(in) stringify_DoubleArrayModel_indent((in), 0)

char* stringify_DoubleArrayModel_list_indent(DoubleArrayModel *in, size_t count, int indent) {
    Jsb jsb = {.pp = indent};
    if (jsb_begin_array(&jsb)) return NULL;
    for (size_t i = 0; i < count; i++) {
        if (_stringify_DoubleArrayModel(&jsb, &in[i])) return NULL;
    }
    if (jsb_end_array(&jsb)) return NULL;
    return jsb_get(&jsb);
}

#define stringify_DoubleArrayModel_list(in, count) stringify_DoubleArrayModel_list_indent((in), (count), 0)

#endif // JSGEN_TESTS_JSGEN_MODELS_G_H
